# Generated by Django 5.1 on 2024-09-20 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('karyawanId', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('gaji', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusKehadiran', models.IntegerField(choices=[(1, 'Hadir'), (2, 'Sakit'), (3, 'Izin')])),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosq.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('karyawan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bosq.karyawan')),
            ],
        ),
    ]
