# Generated by Django 5.1 on 2024-10-01 02:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('karyawan_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=30)),
                ('jabatan', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('gaji', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Overseer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('username', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField(choices=[(1, 'Overseer'), (2, 'Karyawan')])),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusKehadiran', models.IntegerField(choices=[(1, 'Hadir'), (2, 'Sakit'), (3, 'Izin')])),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosq.karyawan')),
            ],
        ),
    ]
