# Generated by Django 5.1 on 2024-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='nama',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
